### ISSUE TITLE
Discord group creation

### ISSUE THREAD

**Issue by GoluLiliput** [spyderbibek/Anime-Zone#1]
Hello brother, 
Is the development of this app active??

**Comment by spyderbibek** [comment]
yes it's active

**Comment by GoluLiliput** [comment]
Are you working for next updates?

**Comment by spyderbibek** [comment]
yes currently fixing bugs and implementing new features

**Comment by GoluLiliput** [comment]
When will the next update come out?

**Comment by spyderbibek** [comment]
still working on it so no ETA

**Comment by GoluLiliput** [comment]
Alright I understand

**Comment by spyderbibek** [comment]
are you using the app??

**Comment by GoluLiliput** [comment]
Yes I am. And honestly I see great potential in the app.

**Comment by spyderbibek** [comment]
You can join our discord through here
https://discord.gg/mCZ7VuS
