### ISSUE TITLE
Please enable the myanimelist sync option 🥺

### ISSUE THREAD

**Issue by Amit29533** [spyderbibek/Anime-Zone#2]
Please 😢 don't discriminate on myanimelist , it shouldn't be wiped , plz enabled that option

**Comment by spyderbibek** [comment]
wipped??? what do you mean..

**Comment by spyderbibek** [comment]
next update will have MAL sync

**Comment by Amit29533** [comment]
Thank you 🥺 so muchhhh...
I appreciate all your efforts

**Comment by GoluLiliput** [comment]
anime zone is easily the best anime app in the entire planet. EASILY....!!!

**Comment by HussamAbuArqoob** [comment]
Hi bro, 
I don't know if this is allowed in public, I want to ask you if you can share the source code for the application or sell it, please know that I don't intend to trade in the source code. I want to use it to create an anime application directed at Arabs only.
I'm waiting for your response
