### ISSUE TITLE
AnimeZone source code

### ISSUE THREAD

**Issue by HussamAbuArqoob** [spyderbibek/Anime-Zone#3]
Hi bro, 
I don't know if this is allowed in public, I want to ask you if you can share the source code for the application or sell it, please know that I don't intend to trade in the source code. I want to use it to create an anime application directed at Arabs only.
I'm waiting for your response

**Comment by spyderbibek** [comment]
Price is $1500 via Bitcoin or Ethereum only. No negotiation. I am sure you
have already seen how high quality the app is with alot of features.

**Comment by GoluLiliput** [comment]
I think the cost would fairly be 2000$ with all discounts applied
