### ISSUE TITLE
Bug: Select Button Doesn't Work

### ISSUE THREAD

**Issue by 8227846265** [spyderbibek/Anime-Zone#6]
Hello, I have a Chromecast with Google TV

After installing the app, the select button on the remote doesn't work thus I can't select any anime nor watch anything. 

Navigation however works fine.

Version: AnimeZone 2.4.0

**Comment by spyderbibek** [comment]
Yes it's a known bug.. Flutter currently doesn't fully support remote control on Android TV. I request you to use mouse and keyboard until i find a solution for this in the future updates.

**Comment by 8227846265** [comment]
Noted. Thank you.

**Comment by Kneesnap** [comment]
Thanks for the response!
